-- Enums (generated by Prisma)
CREATE TYPE "LineItemSource" AS ENUM ('SHEETS', 'WORKSPACE');
CREATE TYPE "LineItemType" AS ENUM ('EXPENSE', 'REVENUE');
CREATE TYPE "LineItemStatus" AS ENUM ('NA', 'PENDING', 'APPROVED', 'DENIED');

-- 1) Add new columns as NULLABLE (or defaulted where harmless)
ALTER TABLE "line_items" ADD COLUMN "committeeId" TEXT;
ALTER TABLE "line_items" ADD COLUMN "price_total_cents" INTEGER;
ALTER TABLE "line_items" ADD COLUMN "type" "LineItemType";

ALTER TABLE "line_items" ADD COLUMN "used" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "line_items" ADD COLUMN "qty" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "line_items" ADD COLUMN "price_unit_opt_cents" INTEGER;
ALTER TABLE "line_items" ADD COLUMN "vendor" TEXT;
ALTER TABLE "line_items" ADD COLUMN "online" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "line_items" ADD COLUMN "link_opt" TEXT;
ALTER TABLE "line_items" ADD COLUMN "notes_opt" TEXT;
ALTER TABLE "line_items" ADD COLUMN "status" "LineItemStatus" NOT NULL DEFAULT 'NA';
ALTER TABLE "line_items" ADD COLUMN "reason_opt" TEXT;
ALTER TABLE "line_items" ADD COLUMN "event_text_opt" TEXT;
ALTER TABLE "line_items" ADD COLUMN "source" "LineItemSource" NOT NULL DEFAULT 'WORKSPACE';
ALTER TABLE "line_items" ADD COLUMN "sheetRowKey" VARCHAR(64);

-- 2) Backfill committeeId by joining through events
UPDATE "line_items" li
SET "committeeId" = e."committeeId"
FROM "events" e
WHERE li."eventId" = e."id" AND li."committeeId" IS NULL;

-- 3) Backfill required scalars with safe defaults
UPDATE "line_items" SET "price_total_cents" = 0 WHERE "price_total_cents" IS NULL;
UPDATE "line_items" SET "type" = 'EXPENSE' WHERE "type" IS NULL;

-- 4) Add FK, then enforce NOT NULL
ALTER TABLE "line_items"
  ADD CONSTRAINT "line_items_committeeId_fkey"
  FOREIGN KEY ("committeeId") REFERENCES "Committee"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "line_items" ALTER COLUMN "committeeId" SET NOT NULL;
ALTER TABLE "line_items" ALTER COLUMN "price_total_cents" SET NOT NULL;
ALTER TABLE "line_items" ALTER COLUMN "type" SET NOT NULL;

-- 5) Helpful indexes (skip if Prisma already added them)
CREATE INDEX IF NOT EXISTS "line_items_committeeId_idx" ON "line_items" ("committeeId");
CREATE INDEX IF NOT EXISTS "line_items_sheetRowKey_idx" ON "line_items" ("sheetRowKey");
